/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chap4.miniProjectA;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author JIKJACK
 */
public class FortueTellingGUI extends javax.swing.JFrame {

    /**
     * Creates new form FortueTellingGUI
     */
    public FortueTellingGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupDay = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rdbMonday = new javax.swing.JRadioButton();
        rdbTuesday = new javax.swing.JRadioButton();
        rdbWednesday = new javax.swing.JRadioButton();
        rdbThursday = new javax.swing.JRadioButton();
        rdbFriday = new javax.swing.JRadioButton();
        rdbSaturday = new javax.swing.JRadioButton();
        rdbSunday = new javax.swing.JRadioButton();
        btnSubmit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tarPer = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tarPerLove = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        lblLove = new javax.swing.JLabel();
        btnEsc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fortue Telling");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 51));
        jLabel1.setText("ทำนายดวงความรักตามวันเกิด");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("วันเกิด");

        btnGroupDay.add(rdbMonday);
        rdbMonday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbMonday.setText("วันจันทร์");

        btnGroupDay.add(rdbTuesday);
        rdbTuesday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbTuesday.setText("วันอังคาร");

        btnGroupDay.add(rdbWednesday);
        rdbWednesday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbWednesday.setText("วันพุธ");

        btnGroupDay.add(rdbThursday);
        rdbThursday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbThursday.setText("วันพฤหัสบดี");

        btnGroupDay.add(rdbFriday);
        rdbFriday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbFriday.setText("วันศุกร์");

        btnGroupDay.add(rdbSaturday);
        rdbSaturday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbSaturday.setText("วันเสาร์");

        btnGroupDay.add(rdbSunday);
        rdbSunday.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rdbSunday.setText("วันอาทิตย์");

        btnSubmit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSubmit.setText("ทำนาย");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("นิสัย");

        tarPer.setEditable(false);
        tarPer.setColumns(20);
        tarPer.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        tarPer.setRows(5);
        jScrollPane1.setViewportView(tarPer);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("นิสัยเวลามีความรัก");

        tarPerLove.setEditable(false);
        tarPerLove.setColumns(20);
        tarPerLove.setFont(new java.awt.Font("Angsana New", 0, 24)); // NOI18N
        tarPerLove.setRows(5);
        jScrollPane2.setViewportView(tarPerLove);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("ระดับความคลั่งรัก");

        lblLove.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        lblLove.setForeground(new java.awt.Color(255, 0, 0));
        lblLove.setText("00%");

        btnEsc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnEsc.setText("ออก");
        btnEsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEscActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbThursday)
                                    .addComponent(rdbMonday)
                                    .addComponent(rdbSunday))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdbTuesday)
                                            .addComponent(rdbFriday))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rdbWednesday)
                                            .addComponent(rdbSaturday)))
                                    .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(lblLove))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(btnEsc, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rdbMonday)
                    .addComponent(rdbTuesday)
                    .addComponent(rdbWednesday))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbThursday)
                    .addComponent(rdbFriday)
                    .addComponent(rdbSaturday))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbSunday)
                    .addComponent(btnSubmit))
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblLove))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnEsc)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        String Per = null, PerLove = null;

        if (rdbMonday.isSelected()) {
            lblLove.setText("90%");
            Per = "ปกติคนที่เกิดวันนี้เป็นคนที่ค่อนข้างแพรวพราว\n"
                    + "เป็นคนที่ค่อนข้างจะรักอิสระ\n"
                    + "ดูเป็นคนเจ้าชู้ไม่รู้ตัว เพราะเป็นคนมีเสน่ห์ วางตัวดี";
            PerLove = "ถ้ามีความรักขึ้นมาล่ะก็ เหมือนเป็นคนละคน!\n"
                    + "จากเสีอตัวใหญ่ พอมีแฟนแล้วจะกลายเป็นแมวน้อย ขี้อ้อน เอาใจ\n"
                    + "อยากได้อะไรจัดให้ทุกอย่าง งอแงกับแฟนเพราะอยากเรียกร้องความสนใจ\n"
                    + "ถ้าคบกันแล้วก็อยากให้ดูแล เอาอกเอาใจซึ่งกันและกัน มือถือนี่ถ้าไม่ล็อกรหัสก็เรียบร้อย!\n"
                    + "เพราะคนเกิดวันนี้จะแอบหึง แอบส่องทุกอย่าง แฟนไปไหน ทำอะไร อยู่กับใคร รู้หมด!\n"
                    + "แต่คนที่เกิดวันจันทร์ถึงจะมีแฟนยังไงก็ยังไม่ทิ้งเพื่อน\n"
                    + "ถ้าอีกฝ่ายเข้าใจ ไม่คิดมากก็คบกันได้ยาว ๆ จ้า";
        } else if (rdbTuesday.isSelected()) {
            lblLove.setText("100%");
            Per = "คนเกิดวันนี้เป็นพ่อแม่บุญทุ่ม เวลารักใครจะจริงจังมากระดับสิบ! \n"
                    + "เป็นคนใจร้อน ตอบช้า 5 นาทีจะรู้สึกใจหายแล้ว ว่าเราพูดอะไรผิดไปไหมนะ? \n"
                    + "หรือว่าเขาไม่อยากคุยกับเราหรือเปล่า? \n"
                    + "หรือว่าเกิดเหตุร้ายอะไรขึ้น เอ๊ะ! หรือว่าแอบคุยกับคนอื่น";
            PerLove = "ถ้าอยู่ในช่วงอินเลิฟแล้วจะอารมณ์ดีทั้งวัน ยิ้มคนเดียว\n"
                    + "เป็นคนติดแฟน อยากอยู่ด้วยตลอดเวลา\n"
                    + "เธออยู่ที่ไหน จะไปอยู่ตรงหน้า จะไปหาแน่ ๆ!\n"
                    + "และค่อนข้างคาดหวังในตัวคนรักมาก ๆ\n"
                    + "ถ้าให้ 100 ต้องได้กลับมา 100\n"
                    + "ชอบอะไรที่แฟร์ ๆ ถ้าไม่แฟร์ก็หาใหม่\n"
                    + "ชอบความตื่นเต้นท้าทาย ถ้าอีกฝ่ายเล่นตัวนิดหน่อย\n"
                    + "เข้าหาบ้าง เอาใจก่อนบ้าง แกล้งไม่ตอบบ้าง\n"
                    + "ยิ่งตื่นเต้น ยิ่งถ้าอีกฝ่ายใส่ใจ\n"
                    + "และเข้าใจในตัวของคนที่เกิดวันอังคาร\n"
                    + "รับรองว่ารักจนมูฟออนไปไหนไม่ได้!";
        } else if (rdbWednesday.isSelected()) {
            lblLove.setText("50%");
            Per = "คารมดีเป็นที่ 1 ตบมุขโบ๊ะบ๊ะได้ ทันคน เทคนิคอ่อยชั้นครู แพรวพราวพอ ๆ กับคน\n"
                    + "เกิดวันจันทร์ เป็นคนที่ค่อย ๆ ดู ค่อย ๆ เก็บข้อมูลฝ่ายตรงข้าม ไม่วู่วาม ชอบนะ แต่ไม่แสดงออกตรง ๆ รอ\n"
                    + "จนกว่าจะแน่ใจจริง ๆ แล้วถึงจะตกลงเป็นแฟน";
            PerLove = "เป็นคนที่รักใครแล้วรักจริง โรแมนติก เรื่องเล็ก ๆ น้อยก็จำได้ เอาใจ\n"
                    + "ใส่แฟนหรือคนรักมาก แต่ข้อเสียของคนที่เกิดวันนี้ เป็นเพราะอีโก้ที่สูงเสียดฟ้า อาจจะทำให้เรื่องราวที่มันไม่ได้\n"
                    + "มีอะไรเลย พังได้ง่าย ๆ เพราะความมีอีโก้ของตัวเอง เวลาโกรธมาก็จะใช้คำพูดที่ไม่ค่อยดี เป็นคนคาดหวังกับ\n"
                    + "ความรักสูง คิดมาก ขี้หึง ขี้ระแวง แล้วพอไม่ได้ตามที่หวัง ก็อาจจะพาลเบื่อได้ง่าย ๆ แนะนำให้ใจเย็น ๆ และ\n"
                    + "ลดความคาดหวังกับอีโก้ลงนิดหน่อย จะทำให้ความรักไปได้ด";
        } else if (rdbThursday.isSelected()) {
            lblLove.setText("60%");
            Per = "ภายนอกอาจจะดูเป็นคนอ่อยเก่ง แพรวพราว แต่จริง ๆ แล้วเป็นคนค่อนข้าง\n"
                    + "อ่อนไหว เป็นคนออกจะบ๊อง ๆ ขาด ๆ เกิน ๆ ด้วยซ้ำ คนเกิดวันนี้ถึงจะดูอ่อยเก่งก็จริง ดูเป็นสาวฮอต หนุ่ม\n"
                    + "ฮอต แต่รักใครแล้วรักจริงจังมาก ไม่ชอบการนอกใจ และการถูกหักหลัง";
            PerLove = "เวลาคนเกิดวันพฤหัสบดีมีความรักแล้วเหมือนเมากัญชา อารมณ์\n"
                    + "ดีทั้งวัน และวันครบรอบ วันเกิด จำได้หมด ตกหลุมรักคนง่าย ยิ่งถ้าเจอคนที่คุยแบบ Deep Conversation \n"
                    + "ได้ ยิ่งชอบ ชอบคนที่เป็นผู้ใหญ่ ยิ่งมีทัศนคติดี ๆ หรือพลังบวก คนที่เกิดวันพฤหัสบดีจะมโนไปถึงขั้นแต่งงาน\n"
                    + "เลย ทั้ง ๆ ที่แค่เริ่มคุย แต่ก็ชอบความรักที่ค่อยเป็นค่อยไป ไม่รีบนะ";
        } else if (rdbFriday.isSelected()) {
            lblLove.setText("85%");
            Per = "คนเกิดวันนี้ออกแนวพ่อบ้านใจกล้า ไม่เถียงหรอกนะ แต่อย่าให้โกรธ! เป็นคนช่าง\n"
                    + "มโน ชอบเพ้อเงียบ ๆ เป็นตุเป็นตะอยู่คนเดียว และคนเกิดวันนี้เป็นคนอ่อนโยน เอาใจใส่แฟนมาก ต้องการให้\n"
                    + "แฟนเอาใจใส่ตัวเองเหมือนกัน ถ้าเจอคนที่ทำให้คนเกิดวันศุกร์รู้สึกรักทั้งแฟน รักทั้งตัวเอง หรือชอบตัวเองตอน\n"
                    + "อยู่กับแฟน จะเป็นอะไรที่เพอร์เฟ็กต์มาก";
            PerLove = "ใครชอบคนสายเปย์ มาทางนี้! คนเกิดวันศุกร์บอกเลยว่าเปย์เก่งงงง \n"
                    + "ชอบหาอะไรทำ ชวนแฟนทำนู่น ทำนี่ อยู่ด้วยแล้วไม่มีทางเบื่อแน่นอน และมักจะเจอคนที่แตกต่างกันที่ อายุ \n"
                    + "เชื้อชาติ ศาสนา ฐานะ ฯลฯ แต่ไม่ค่อยสนใจเท่าไร ถ้าพร้อมจะเดินไปด้วยกันก็โอเค คบกันได้ยาว ๆ";
        } else if (rdbSaturday.isSelected()) {
            lblLove.setText("70%");
            Per = "คนที่เกิดวันเสาร์ชอบทำตัวเป็นผู้นำ อีโก้สูง บ้าพลัง ไม่ชอบคนต่อล้อต่อเถียง ฉะนั้น\n"
                    + "คนที่นิ่ง ๆ สุขุมหน่อย ๆ ก็จะเข้าทางคนที่เกิดวันนี้ เป็นคนเด็ดขาด ชัดเจน ชอบก็คือชอบ ไม่ยึก ๆ ยัก ๆ ชอบ\n"
                    + "คนเอาใจ ใส่ใจ ชอบอะไรที่เรียบง่าย มั่นคง ถ้ามีแฟนแล้วก็จะทุ่มสุด ๆ";
            PerLove = "อยากได้อะไรบอกจะจัดให้ตามที่ขอทุกอย่าง ยกเว้นให้ลุงลาออก \n"
                    + "(เอ๊ย! ไม่ใช่!) ดูแลแฟนหรือคนรักดีเว่อร์! เหมือนเราเป็นเจ้าหญิงหรือเจ้าชาย แต่ไม่ชอบอะไรที่จุกจิก ชนิดว่า\n"
                    + "ตามหึงตามจิกเกินเบอร์จะเบื่อมาก แต่ถึงจะไม่ชอบอะไรแบบนั้น คนที่เกิดวันเสาร์เวลาหึงจะน่ากลัวระดับสิบ!";
        } else if (rdbSunday.isSelected()) {
            lblLove.setText("75%");
            Per = "คนที่เกิดวันอาทิตย์ เขาว่าเป็นคนอารมณ์ขึ้น ๆ ลง ๆ อาจจะตามอารมณ์ยากสัก\n"
                    + "หน่อย เป็นคนใจกว้าง ให้อิสระกับคนรัก แต่ถ้าเข้าโหมดจริงจังแล้วไม่ชอบอะไรเล่น ๆ อยู่ไหน ทำอะไรกับใคร \n"
                    + "ต้องบอก ต้องรายงาน และถ้าชอบใครก็จะทำทุกวิถีทางเพื่อให้ได้คบ";
            PerLove = "พอมีแฟนแล้วโลกสดใส อะไรก็เป็นสีชมพูไปหมด ถ้ามีแฟนจะขี้\n"
                    + "บ่นมาก ๆ แต่ก็เป็นเพราะรักแหละถึงบ่น เป็นคนรักเดียวใจเดียว คบใครก็คบทีละคน ไม่ได้หว่านไปทั่วถ้าเทียบ\n"
                    + "กับคนเกิดวันอื่น ๆ ถ้าเจอแฟนหรือคนรักที่เข้ากับครอบครัวหรือเพื่อนได้ก็ผ่านฉลุย เพราะชอบความรักแบบ\n"
                    + "ลึกซึ้ง พร้อมที่จะเป็นครอบครัวเดียวกันในอนาคต ชอบคนพูดเพราะ ใส่ใจ ยิ้มหวาน ถ้าสอบผ่านก็จะเสมอต้น\n"
                    + "เสมอปลายกับคนรักมาก ๆ";
        } else {
            lblLove.setText("-100%");
            JOptionPane.showMessageDialog(rootPane, "กรุณาเลือกวันเกิดของคุณ");
            Per = "ใจร้อนนะเราอะ";
            PerLove = "เลือกวันเกิดก่อนนะ";
        }

        tarPer.setText("" + Per);
        tarPerLove.setText("" + PerLove);

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnEscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEscActionPerformed
        int option = JOptionPane.showConfirmDialog(rootPane, "ต้องการปิด?");
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnEscActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FortueTellingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FortueTellingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FortueTellingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FortueTellingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FortueTellingGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEsc;
    private javax.swing.ButtonGroup btnGroupDay;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblLove;
    private javax.swing.JRadioButton rdbFriday;
    private javax.swing.JRadioButton rdbMonday;
    private javax.swing.JRadioButton rdbSaturday;
    private javax.swing.JRadioButton rdbSunday;
    private javax.swing.JRadioButton rdbThursday;
    private javax.swing.JRadioButton rdbTuesday;
    private javax.swing.JRadioButton rdbWednesday;
    private javax.swing.JTextArea tarPer;
    private javax.swing.JTextArea tarPerLove;
    // End of variables declaration//GEN-END:variables
}
